version: '3.8'

services:
  api:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - redis
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_CA_PATH: ../../ca.pem
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - app-network
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
